name: Flutter CI Pipeline

on:
  push:
    branches: [main] # jab bhi main branch me push hoga, pipeline chalega

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Run Analyzer
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        festival: [diwali, holi, default]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK for ${{ matrix.festival }} theme
        run: flutter build apk --release --dart-define=FESTIVAL=${{ matrix.festival }}

      - name: Upload ${{ matrix.festival }} APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.festival }}-apk
          path: build/app/outputs/flutter-apk/app-release.apk
