name: Flutter CI Pipeline

on:
  push:
    branches: [main] # jab bhi main branch me push hoga, pipeline chalega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Run Analyzer (optional)
        run: flutter analyze

      - name: Run Tests (optional)
        run: flutter test

      - name: Build APK with Diwali theme
        run: flutter build apk --release --dart-define=FESTIVAL=diwali

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: diwali-apk
          path: build/app/outputs/flutter-apk/app-release.apk
